'use client';
import { useEffect,useMemo,useState } from 'react';
import { Plus } from 'lucide-react';
import { PageHeader } from '@/components/PageHeader';
import { Modal } from '@/components/Modal';
import { FileUploader } from '@/components/FileUploader';
import { useAuth } from '@/components/AuthProvider';
import { apiFetch } from '@/lib/api-client';
import { AttachmentGallery } from '@/components/AttachmentGallery';

export default function Page(){
  const {accessToken,me}=useAuth();const isAdmin=!!me?.roles.includes('admin');const [rows,setRows]=useState<any[]>([]);const [employees,setEmployees]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [compose,setCompose]=useState(false);const [filter,setFilter]=useState('open');const [err,setErr]=useState('');
  async function load(){try{setErr('');setRows(await apiFetch<any[]>('/api/internal-messages',accessToken));if(isAdmin)setEmployees(await apiFetch<any[]>('/api/options?type=employees',accessToken))}catch(e){setErr((e as Error).message)}}
  async function open(x:any){try{const d=await apiFetch<any>(`/api/internal-messages?id=${x.id}`,accessToken);const files=await apiFetch<any[]>(`/api/files?entity_type=internal_message&entity_id=${x.id}`,accessToken).catch(()=>[]);setSelected({...d,files});await load()}catch(e){setErr((e as Error).message)}}
  useEffect(()=>{load()},[accessToken,isAdmin]);
  const f=useMemo(()=>rows.filter(x=>filter==='all'||(filter==='open'?x.status!=='Geklärt':x.status==='Geklärt')),[rows,filter]);
  return <><PageHeader eyebrow="INTERNE KOMMUNIKATION" title="Nachrichten" text={isAdmin?'Direkte Nachrichten zwischen Administrator und Mitarbeitern.':'Direkte Nachrichten an den Administrator.'} actions={<button className="btn primary" onClick={()=>setCompose(true)}><Plus size={17}/> Neue Nachricht</button>}/>{err&&<div className="alert error">{err}</div>}<div className="workspace-toolbar"><div className="segmented"><button className={filter==='open'?'active':''} onClick={()=>setFilter('open')}>Offen</button><button className={filter==='done'?'active':''} onClick={()=>setFilter('done')}>Geklärt</button><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Alle</button></div></div><div className="workspace-list">{f.map(x=><button className="workspace-row" key={x.id} onClick={()=>open(x)}><div className="grow"><div className="workspace-row-head"><strong>{x.subject}</strong><span className={`badge ${!x.read_at&&x.last_sender_id!==me?.id?'red':''}`}>{x.status}</span></div><p>{x.body}</p><small>{isAdmin?(x.sender_id===me?.id?`An: ${x.recipient?.full_name}`:`Von: ${x.sender?.full_name}`):x.sender_id===me?.id?'An: Administrator':'Von: Administrator'} · {new Date(x.created_at).toLocaleString('de-DE')}</small></div></button>)}</div>{!f.length&&<div className="card empty">Keine Nachrichten vorhanden.</div>}{compose&&<Compose isAdmin={isAdmin} employees={employees} accessToken={accessToken} onClose={()=>setCompose(false)} onSaved={()=>{setCompose(false);load()}}/>}{selected&&<Thread data={selected} me={me} accessToken={accessToken} onClose={()=>setSelected(null)} onChanged={()=>open(selected)}/>}</>
}
function Compose({isAdmin,employees,accessToken,onClose,onSaved}:{isAdmin:boolean;employees:any[];accessToken:string;onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState<any>({recipient_id:'',subject:'',body:''});const [err,setErr]=useState('');async function save(){try{await apiFetch('/api/internal-messages',accessToken,{method:'POST',body:JSON.stringify(f)});onSaved()}catch(e){setErr((e as Error).message)}}return <Modal title="Neue Nachricht" onClose={onClose} footer={<><button className="btn" onClick={onClose}>Abbrechen</button><button className="btn primary" onClick={save}>Senden</button></>}><div className="form-grid">{isAdmin&&<label className="span-2">Empfänger<select value={f.recipient_id} onChange={e=>setF({...f,recipient_id:e.target.value})}><option value="">Mitarbeiter auswählen…</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label>}<label className="span-2">Betreff<input value={f.subject} onChange={e=>setF({...f,subject:e.target.value})}/></label><label className="span-2">Nachricht<textarea value={f.body} onChange={e=>setF({...f,body:e.target.value})}/></label></div>{err&&<div className="alert error">{err}</div>}</Modal>}
function Thread({data,me,accessToken,onClose,onChanged}:{data:any;me:any;accessToken:string;onClose:()=>void;onChanged:()=>void}){const [body,setBody]=useState('');const [err,setErr]=useState('');async function reply(){try{await apiFetch('/api/internal-messages',accessToken,{method:'PATCH',body:JSON.stringify({id:data.id,action:'reply',body})});setBody('');onChanged()}catch(e){setErr((e as Error).message)}}async function resolve(){await apiFetch('/api/internal-messages',accessToken,{method:'PATCH',body:JSON.stringify({id:data.id,action:'resolve'})});onClose()}return <Modal title={data.subject} onClose={onClose}><div className="message-thread"><div className="comment"><strong>{data.sender?.full_name}</strong><small>{new Date(data.created_at).toLocaleString('de-DE')}</small><p>{data.body}</p></div>{(data.internal_message_replies||[]).map((r:any)=><div className="comment" key={r.id}><strong>{r.sender?.full_name}</strong><small>{new Date(r.created_at).toLocaleString('de-DE')}</small><p>{r.body}</p></div>)}</div><div className="card soft" style={{marginTop:12}}><strong>Bilder / Anhänge</strong><div style={{marginTop:8}}><FileUploader entityType="internal_message" entityId={data.id} category="message_photo" accept="image/*,.pdf" label="Bilder / Dateien auswählen" onUploaded={onChanged}/></div><AttachmentGallery files={data.files||[]} accessToken={accessToken}/></div><div className="form-grid"><label className="span-2">Antwort<textarea value={body} onChange={e=>setBody(e.target.value)}/></label></div><div className="toolbar"><button className="btn primary" onClick={reply}>Antwort senden</button><button className="btn" onClick={resolve}>Als geklärt markieren</button></div>{err&&<div className="alert error">{err}</div>}</Modal>}
