'use client';
import { useEffect,useMemo,useState } from 'react';
import { Download,Play,Square,Repeat,Plus } from 'lucide-react';
import { PageHeader } from '@/components/PageHeader';
import { Modal } from '@/components/Modal';
import { useAuth } from '@/components/AuthProvider';
import { apiFetch } from '@/lib/api-client';

function hm(m:number){const sign=m<0?'-':'';m=Math.abs(Math.round(m||0));return `${sign}${Math.floor(m/60)}:${String(m%60).padStart(2,'0')}`}
function today(){return new Date().toISOString().slice(0,10)}

export default function TimePage(){
  const {accessToken,has,me}=useAuth();
  const [period,setPeriod]=useState<'week'|'month'|'year'>('month');
  const [ref,setRef]=useState(new Date().toISOString().slice(0,7));
  const [employees,setEmployees]=useState<any[]>([]);const [sites,setSites]=useState<any[]>([]);
  const [userId,setUserId]=useState(me?.id||'');const [data,setData]=useState<any>({entries:[],summary:{}});
  const [clock,setClock]=useState<any>({day:null,current:null,segments:[]});const [absenceModal,setAbsenceModal]=useState(false);const [manualModal,setManualModal]=useState(false);const [error,setError]=useState('');

  const canAll=has('time.all')||has('time.correct');
  async function load(){try{setError('');const q=new URLSearchParams({period,ref});if(userId)q.set('user_id',userId);setData(await apiFetch(`/api/time-entries?${q}`,accessToken));}catch(e){setError((e as Error).message)}}
  async function loadClock(){if(!me?.id)return;try{setClock(await apiFetch('/api/time-clock',accessToken))}catch(e){setError((e as Error).message)}}
  useEffect(()=>{if(!userId&&me)setUserId(me.id)},[me]);
  useEffect(()=>{apiFetch<any[]>('/api/options?type=sites',accessToken).then(setSites).catch(()=>{});if(canAll||has('absence.manage'))apiFetch<any[]>('/api/options?type=employees',accessToken).then(setEmployees).catch(()=>{})},[accessToken,canAll]);
  useEffect(()=>{if(userId)load()},[period,ref,userId,accessToken]);
  useEffect(()=>{loadClock()},[accessToken,me?.id]);

  function changePeriod(p:'week'|'month'|'year'){setPeriod(p);if(p==='week')setRef(today());else if(p==='month')setRef(today().slice(0,7));else setRef(today().slice(0,4))}
  async function download(format:'pdf'|'xlsx'){try{setError('');const q=new URLSearchParams({format,period,ref});if(userId)q.set('user_id',userId);const r=await fetch(`/api/time-entries/export?${q}`,{headers:{Authorization:`Bearer ${accessToken}`}});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error||`HTTP ${r.status}`)}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=(r.headers.get('Content-Disposition')?.match(/filename="([^"]+)"/)?.[1])||`Arbeitszeiten.${format}`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}catch(e){setError((e as Error).message)}}

  const s=data.summary||{};
  return <><PageHeader eyebrow="PERSONAL" title="Zeiterfassung" text="Arbeitszeiten der Mitarbeiter werden über die Stempeluhr mit Systemzeit erfasst. Pausen werden automatisch abgezogen." actions={<><button className="btn" onClick={()=>download('pdf')}><Download size={16}/> PDF</button><button className="btn" onClick={()=>download('xlsx')}><Download size={16}/> Excel</button><button className="btn" onClick={()=>setAbsenceModal(true)}>Urlaub / Krankheit</button>{has('time.correct')&&<button className="btn" onClick={()=>setManualModal(true)}><Plus size={16}/> Admin-Korrektur</button>}</>}/>{error&&<div className="alert error">{error}</div>}
  {userId===me?.id&&<ClockPanel accessToken={accessToken} sites={sites} clock={clock} reload={async()=>{await loadClock();await load()}}/>}
  <div className="card time-filter-card"><div className="section-title"><h2>Übersicht & Export</h2></div><div className="toolbar"><div className="segmented"><button className={period==='week'?'active':''} onClick={()=>changePeriod('week')}>Woche</button><button className={period==='month'?'active':''} onClick={()=>changePeriod('month')}>Monat</button><button className={period==='year'?'active':''} onClick={()=>changePeriod('year')}>Jahr</button></div>{period==='week'&&<input type="date" value={ref.slice(0,10)} onChange={e=>setRef(e.target.value)}/>} {period==='month'&&<input type="month" value={ref.slice(0,7)} onChange={e=>setRef(e.target.value)}/>} {period==='year'&&<input type="number" min="2020" max="2100" value={ref.slice(0,4)} onChange={e=>setRef(e.target.value)}/>} {canAll&&<select value={userId} onChange={e=>setUserId(e.target.value)}>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select>}</div></div>
  <div className="stats"><div className="stat"><span>Soll</span><strong>{hm(s.targetMinutes||0)}</strong><small>{period==='week'?'Wochenziel':period==='year'?'Jahresziel':'Monatsziel'}</small></div><div className="stat"><span>Ist</span><strong>{hm(s.actualMinutes||0)}</strong><small>gestempelte Arbeitszeit</small></div><div className="stat"><span>Abwesenheit</span><strong>{hm(s.absenceCreditMinutes||0)}</strong><small>gutgeschriebene Sollzeit</small></div><div className="stat"><span>Überstunden</span><strong>{hm(s.overtimeMinutes||0)}</strong><small>Soll / Ist inkl. Abwesenheit</small></div><div className="stat"><span>Urlaub</span><strong>{s.absenceDays?.Urlaub||0}</strong><small>Arbeitstage</small></div><div className="stat"><span>Krank</span><strong>{s.absenceDays?.Krankheit||0}</strong><small>Arbeitstage</small></div></div>
  <div className="card"><div className="section-title"><h2>Zeitbuchungen</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Datum</th><th>Baustelle</th><th>Unterkategorie</th><th>Von</th><th>Bis</th><th>Pause</th><th>Gesamt</th><th>Quelle</th></tr></thead><tbody>{data.entries?.map((x:any)=><tr key={x.id}><td>{new Date(x.work_date+'T12:00:00').toLocaleDateString('de-DE')}</td><td>{x.construction_sites?.title||'Allgemein'}</td><td>{x.section?.name||'Allgemein'}</td><td>{String(x.start_time).slice(0,5)}</td><td>{String(x.end_time).slice(0,5)}</td><td>{x.pause_minutes} min</td><td><strong>{hm(x.total_minutes)} h</strong></td><td>{x.source_kind==='clock'?<span className="badge green">Stempeluhr</span>:x.source_report_id?<span className="badge">Rapport</span>:<span className="badge amber">Admin</span>}</td></tr>)}</tbody></table></div></div>
  {absenceModal&&<AbsenceModal accessToken={accessToken} userId={userId} employees={employees} canManage={has('absence.manage')} onClose={()=>setAbsenceModal(false)} onSaved={()=>{setAbsenceModal(false);load()}}/>}
  {manualModal&&<ManualTimeModal accessToken={accessToken} userId={userId} employees={employees} sites={sites} onClose={()=>setManualModal(false)} onSaved={()=>{setManualModal(false);load()}}/>}</>
}

function ClockPanel({accessToken,sites,clock,reload}:{accessToken:string;sites:any[];clock:any;reload:()=>void}){
  const [siteId,setSiteId]=useState('');const [sectionId,setSectionId]=useState('');const [sections,setSections]=useState<any[]>([]);const [activity,setActivity]=useState('');const [err,setErr]=useState('');const [now,setNow]=useState(Date.now());
  useEffect(()=>{const i=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(i)},[]);
  useEffect(()=>{if(!siteId){setSections([]);setSectionId('');return}apiFetch<any[]>(`/api/project-sections?site_id=${siteId}`,accessToken).then(setSections).catch(()=>setSections([]))},[siteId,accessToken]);
  async function act(action:'start'|'switch'|'stop'){try{setErr('');await apiFetch('/api/time-clock',accessToken,{method:'POST',body:JSON.stringify({action,construction_site_id:siteId||null,section_id:sectionId||null,activity:activity||null})});setActivity('');reload()}catch(e){setErr((e as Error).message)}}
  const running=clock?.day?.status==='running';const elapsed=running?Math.max(0,Math.floor((now-new Date(clock.day.started_at).getTime())/60000)):0;
  return <div className={`card clock-card ${running?'running':''}`}><div className="section-title"><div><h2>Stempeluhr</h2><p className="muted">{running?`Arbeitstag läuft seit ${new Date(clock.day.started_at).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}`:'Noch nicht gestartet'}</p></div>{running&&<strong className="clock-live">{hm(elapsed)} h</strong>}</div>{running&&clock.current&&<div className="clock-current"><span>Aktuell</span><strong>{clock.current.construction_sites?.title||'Allgemeine Tätigkeit'}{clock.current.section?.name?` · ${clock.current.section.name}`:''}</strong><small>{clock.current.activity||'ohne Tätigkeitsangabe'}</small></div>}<div className="form-grid clock-form"><label>Baustelle<select value={siteId} onChange={e=>{setSiteId(e.target.value);setSectionId('')}}><option value="">Kleinauftrag / freie Tätigkeit / Betrieb</option>{sites.map(s=><option key={s.id} value={s.id}>{s.project_no} · {s.title}</option>)}</select></label><label>Unterkategorie<select value={sectionId} onChange={e=>setSectionId(e.target.value)} disabled={!siteId}><option value="">Allgemein</option>{sections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="span-2">Tätigkeit / Hinweis<input value={activity} onChange={e=>setActivity(e.target.value)} placeholder="z. B. Montage Türen, Rückfahrt / Ausladen"/></label></div><div className="clock-actions">{!running?<button className="btn clock-start" onClick={()=>act('start')}><Play size={20}/> Arbeitstag starten</button>:<><button className="btn primary" onClick={()=>act('switch')}><Repeat size={18}/> Auftrag / Tätigkeit wechseln</button><button className="btn dark" onClick={()=>act('stop')}><Square size={18}/> Feierabend / Stopp</button></>}</div>{running&&<div className="alert success">Die aktuell gewählte Baustelle läuft weiter – einschließlich Rückfahrt, Ausladen und auftragsbezogener Nacharbeit – bis du aktiv wechselst oder den Arbeitstag stoppst.</div>}{err&&<div className="alert error">{err}</div>}<div className="muted clock-break-note">Automatische Pause: bis 5,5 h = 15 Min. (09:30–09:45), ab 5,5 h = 45 Min. (zusätzlich 12:30–13:00).</div></div>
}

function AbsenceModal({accessToken,userId,employees,canManage,onClose,onSaved}:{accessToken:string;userId:string;employees:any[];canManage:boolean;onClose:()=>void;onSaved:()=>void}){const t=today();const [f,setF]=useState<any>({user_id:userId,absence_type:'Urlaub',start_date:t,end_date:t,status:'Genehmigt',notes:''});const [list,setList]=useState<any[]>([]);const [err,setErr]=useState('');useEffect(()=>{apiFetch<any[]>(`/api/absences?user_id=${f.user_id}`,accessToken).then(setList).catch(e=>setErr(e.message))},[f.user_id]);async function save(){try{await apiFetch('/api/absences',accessToken,{method:'POST',body:JSON.stringify(f)});onSaved()}catch(e){setErr((e as Error).message)}}return <Modal title="Urlaub & Krankheit" onClose={onClose} footer={<><button className="btn" onClick={onClose}>Schließen</button><button className="btn primary" onClick={save}>Buchen</button></>}><div className="form-grid">{canManage&&<label>Mitarbeiter<select value={f.user_id} onChange={e=>setF({...f,user_id:e.target.value})}><option value={userId}>Eigene Auswahl</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label>}<label>Art<select value={f.absence_type} onChange={e=>setF({...f,absence_type:e.target.value})}>{(canManage?['Urlaub','Krankheit','Freizeitausgleich','Berufsschule','Sonstiges']:['Urlaub','Krankheit']).map(x=><option key={x}>{x}</option>)}</select></label><label>Von<input type="date" value={f.start_date} onChange={e=>setF({...f,start_date:e.target.value})}/></label><label>Bis<input type="date" value={f.end_date} onChange={e=>setF({...f,end_date:e.target.value})}/></label><label className="span-2">Bemerkung<textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label></div><div className="alert success">Je Arbeitstag wird automatisch die individuelle tägliche Sollzeit gutgeschrieben (Wochenstunden ÷ 5).</div>{err&&<div className="alert error">{err}</div>}<div className="table-wrap" style={{marginTop:18}}><table className="table"><thead><tr><th>Art</th><th>Von</th><th>Bis</th><th>Status</th></tr></thead><tbody>{list.map(x=><tr key={x.id}><td>{x.absence_type}</td><td>{x.start_date}</td><td>{x.end_date}</td><td>{x.status}</td></tr>)}</tbody></table></div></Modal>}

function ManualTimeModal({accessToken,userId,employees,sites,onClose,onSaved}:{accessToken:string;userId:string;employees:any[];sites:any[];onClose:()=>void;onSaved:()=>void}){const t=today();const [f,setF]=useState<any>({user_id:userId,work_date:t,start_time:'07:00',end_time:'15:30',pause_minutes:45,travel_setup_minutes:0,construction_site_id:'',activity:'',notes:'',locked:true});const [err,setErr]=useState('');async function save(){try{await apiFetch('/api/time-entries',accessToken,{method:'POST',body:JSON.stringify(f)});onSaved()}catch(e){setErr((e as Error).message)}}return <Modal title="Admin-Zeitkorrektur / Nachtrag" onClose={onClose} footer={<><button className="btn" onClick={onClose}>Abbrechen</button><button className="btn primary" onClick={save}>Speichern</button></>}><div className="alert amber">Manuelle Zeiteingabe ist ausschließlich für Admin/Korrekturberechtigte vorgesehen.</div><div className="form-grid"><label>Mitarbeiter<select value={f.user_id} onChange={e=>setF({...f,user_id:e.target.value})}>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label><label>Datum<input type="date" value={f.work_date} onChange={e=>setF({...f,work_date:e.target.value})}/></label><label>Baustelle<select value={f.construction_site_id} onChange={e=>setF({...f,construction_site_id:e.target.value})}><option value="">Allgemein</option>{sites.map(s=><option key={s.id} value={s.id}>{s.project_no} · {s.title}</option>)}</select></label><label>Von<input type="time" value={f.start_time} onChange={e=>setF({...f,start_time:e.target.value})}/></label><label>Bis<input type="time" value={f.end_time} onChange={e=>setF({...f,end_time:e.target.value})}/></label><label>Pause<input type="number" step="15" value={f.pause_minutes} onChange={e=>setF({...f,pause_minutes:Number(e.target.value)})}/></label><label className="span-2">Tätigkeit<input value={f.activity} onChange={e=>setF({...f,activity:e.target.value})}/></label><label className="span-2">Bemerkung<textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label></div>{err&&<div className="alert error">{err}</div>}</Modal>}
