import { NextRequest, NextResponse } from 'next/server';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { ApiError, audit, errorResponse, requireUser } from '@/lib/api-auth';
import { supabaseAdmin } from '@/lib/supabase-server';
import { RAPPORT_HEADER_QR_PNG_BASE64 } from '@/lib/logo-data';
import { requireReportAccess } from '@/lib/entity-access';
export const runtime='nodejs'; export const dynamic='force-dynamic';
const safe=(v:any)=>String(v??''); const hm=(v:number)=>`${Math.floor((v||0)/60)}:${String((v||0)%60).padStart(2,'0')}`;
const fmtDate=(v:any)=>{if(!v)return '—';try{return new Intl.DateTimeFormat('de-DE').format(new Date(String(v).slice(0,10)+'T12:00:00'))}catch{return safe(v)}};
function wrap(text:string,max:number){if(!text)return ['—'];const words=text.split(/\s+/),lines:string[]=[];let cur='';for(const w of words){if((cur+' '+w).trim().length>max){if(cur)lines.push(cur);cur=w}else cur=(cur+' '+w).trim()}if(cur)lines.push(cur);return lines}
export async function POST(req:NextRequest){try{
 const u=await requireUser(req,'reports.read');const {id}=await req.json();await requireReportAccess(u,id);const db=supabaseAdmin();
 const {data:r,error}=await db.from('work_reports').select('*,construction_sites(project_no,title,street,postal_code,city,customers(name,salutation,street,postal_code,city)),section:project_sections(id,name),work_report_members(*,profiles(full_name)),work_report_materials(*)').eq('id',id).single();if(error||!r)throw error||new ApiError(404,'Rapport nicht gefunden.');
 const {data:settings}=await db.from('portal_settings').select('*').eq('id',1).maybeSingle();
 const pdf=await PDFDocument.create(),page=pdf.addPage([595.28,841.89]);const {width,height}=page.getSize();const regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);
 const red=rgb(.91,.08,.11),black=rgb(.04,.05,.06),gray=rgb(.38,.41,.45),light=rgb(.965,.968,.972),line=rgb(.82,.83,.85),white=rgb(1,1,1);const L=34,R=561,W=R-L;let y=height-34;
 const txt=(t:string,x:number,yy:number,size=8,font=regular,color=black)=>page.drawText(t||'—',{x,y:yy,size,font,color});
 const label=(t:string,x:number,yy:number)=>txt(t.toUpperCase(),x,yy,7,bold,black);
 const rule=(yy:number,color=line,th=.7)=>page.drawLine({start:{x:L,y:yy},end:{x:R,y:yy},thickness:th,color});
 const box=(x:number,yy:number,w:number,h:number)=>page.drawRectangle({x,y:yy,width:w,height:h,color:white,borderColor:line,borderWidth:.7});
 const headerLogo=await pdf.embedPng(Buffer.from(RAPPORT_HEADER_QR_PNG_BASE64,'base64'));const hd=headerLogo.scaleToFit(527,76);
page.drawImage(headerLogo,{x:L,y:height-108,width:hd.width,height:hd.height});
page.drawText('ARBEITSBERICHT',{x:L,y:height-148,size:24,font:bold,color:black});
page.drawText('Rapport',{x:L,y:height-168,size:9,font:regular,color:gray});
page.drawText(safe(r.report_no),{x:L+43,y:height-168,size:9,font:bold,color:red});
page.drawText(`Unterkategorie: ${safe(r.section?.name||'Allgemein')}`,{x:300,y:height-168,size:9,font:regular,color:gray});
y=height-190;rule(y,red,1.2);y-=18;
 const gap=12,bw=(W-gap)/2,bh=76;box(L,y-bh,bw,bh);box(L+bw+gap,y-bh,bw,bh);
 label('Auftraggeber',L+14,y-17);label('Ausführungsort',L+bw+gap+14,y-17);
 const cust=`${safe(r.customer_salutation||r.construction_sites?.customers?.salutation)} ${safe(r.customer_name||r.construction_sites?.customers?.name)}`.trim();txt(cust,L+14,y-38,10,bold);txt(safe(r.construction_sites?.title||r.customer_name||'Freier Rapport'),L+bw+gap+14,y-38,10,bold);
 txt(safe(r.construction_sites?.customers?.street||r.customer_street),L+14,y-54,8);txt(`${safe(r.construction_sites?.customers?.postal_code||r.customer_postal_code)} ${safe(r.construction_sites?.customers?.city||r.customer_city)}`.trim(),L+14,y-66,8);txt(safe(r.construction_sites?.street||r.customer_street),L+bw+gap+14,y-54,8);txt(`${safe(r.construction_sites?.postal_code||r.customer_postal_code)} ${safe(r.construction_sites?.city||r.customer_city)}`.trim(),L+bw+gap+14,y-66,8);y-=96;
 label('Arbeitsbeschreibung / ausgeführte Arbeiten',L,y);y-=12;const dlines=wrap(safe(r.work_description),96).slice(0,4),dh=Math.max(42,18+dlines.length*11);box(L,y-dh,W,dh);let dy=y-17;for(const s of dlines){txt(s,L+10,dy,8.5);dy-=11}y-=dh+20;
 label('Arbeitszeit',L,y);y-=13;const widths=[145,63,63,66,78,72],xs=[L];for(const w of widths)xs.push(xs[xs.length-1]+w);const headH=22,rowH=22,members=(r.work_report_members||[]).slice(0,8);page.drawRectangle({x:L,y:y-headH,width:W,height:headH,color:light,borderColor:line,borderWidth:.7});['Datum / Name','von','bis','Pause','Fahrt/Rüst','Gesamt'].forEach((h,i)=>txt(h,xs[i]+7,y-14,7,bold,black));for(let i=1;i<xs.length-1;i++)page.drawLine({start:{x:xs[i],y:y-headH},end:{x:xs[i],y:y},thickness:.5,color:line});y-=headH;
 for(const m of members){box(L,y-rowH,W,rowH);const vals=[`${fmtDate(r.work_date)}  ${safe(m.profiles?.full_name)}`,safe(m.start_time).slice(0,5),safe(m.end_time).slice(0,5),`${m.pause_minutes||0} min`,`${m.travel_setup_minutes||0} min`,`${hm(m.total_minutes)} h`];vals.forEach((v,i)=>txt(v,xs[i]+7,y-14,7.5,i===5?bold:regular));for(let i=1;i<xs.length-1;i++)page.drawLine({start:{x:xs[i],y:y-rowH},end:{x:xs[i],y:y},thickness:.5,color:line});y-=rowH}y-=20;
 label('Verarbeitetes Material',L,y);y-=13;const mx=[L,L+75,L+165,R];page.drawRectangle({x:L,y:y-22,width:W,height:22,color:light,borderColor:line,borderWidth:.7});['Menge','Einheit','Beschreibung'].forEach((h,i)=>txt(h,mx[i]+7,y-14,7,bold));y-=22;for(const m of (r.work_report_materials||[]).slice(0,8)){box(L,y-21,W,21);txt(safe(m.quantity),mx[0]+7,y-14,7.5);txt(safe(m.unit),mx[1]+7,y-14,7.5);txt(safe(m.description).slice(0,72),mx[2]+7,y-14,7.5);y-=21}y-=20;
 label('Bemerkungen',L,y);y-=13;const rem=wrap(safe(r.remarks),100).slice(0,3),rh=Math.max(34,16+rem.length*10);box(L,y-rh,W,rh);dy=y-16;for(const s of rem){txt(s,L+10,dy,8);dy-=10}y-=rh+10;
 const statusH=32,sw=(W-gap)/2;box(L,y-statusH,sw,statusH);box(L+sw+gap,y-statusH,sw,statusH);const checked=r.work_completed===true;txt(checked?'[X]':'[ ]',L+14,y-21,15,bold,checked?red:black);txt('Arbeiten abgeschlossen',L+38,y-20,8,checked?bold:regular);const not=r.work_completed===false;txt(not?'[X]':'[ ]',L+sw+gap+14,y-21,15,bold,not?red:black);txt('Arbeiten nicht abgeschlossen',L+sw+gap+38,y-20,8,not?bold:regular);y-=statusH+18;
 const {data:sigFiles}=await db.from('files').select('*').eq('entity_type','report').eq('entity_id',r.id).eq('upload_status','ready').in('category',['signature_customer','signature_employee']).order('created_at',{ascending:false});
 async function drawSig(category:string,x:number,w:number){const f=(sigFiles||[]).find((z:any)=>z.category===category);if(!f)return;const {data:blob,error:de}=await db.storage.from('schunk-private').download(f.storage_path);if(de||!blob)return;try{const im=await pdf.embedPng(new Uint8Array(await blob.arrayBuffer()));const d=im.scaleToFit(w-82,42);page.drawImage(im,{x:x+72+(w-82-d.width)/2,y:y-45,width:d.width,height:d.height})}catch{}}
 const sigW=(W-gap)/2;label('Datum / Unterschrift Auftraggeber (Kunde)',L,y);label('Datum / Unterschrift Auftragnehmer',L+sigW+gap,y);txt(fmtDate(r.work_date),L,y-42,8);txt(fmtDate(r.work_date),L+sigW+gap,y-42,8);await drawSig('signature_customer',L,sigW);await drawSig('signature_employee',L+sigW+gap,sigW);page.drawLine({start:{x:L,y:y-50},end:{x:L+68,y:y-50},thickness:.7,color:gray});page.drawLine({start:{x:L+78,y:y-50},end:{x:L+sigW,y:y-50},thickness:.7,color:gray});page.drawLine({start:{x:L+sigW+gap,y:y-50},end:{x:L+sigW+gap+68,y:y-50},thickness:.7,color:gray});page.drawLine({start:{x:L+sigW+gap+78,y:y-50},end:{x:R,y:y-50},thickness:.7,color:gray});txt('Datum',L,y-61,6,regular,gray);txt('Unterschrift',L+78,y-61,6,regular,gray);txt('Datum',L+sigW+gap,y-61,6,regular,gray);txt('Unterschrift',L+sigW+gap+78,y-61,6,regular,gray);y-=80;
 const legal='Der Kunde / Bevollmächtigte erkennt mit seiner Unterschrift die Arbeitszeit und den Materialverbrauch an. Ebenso wird die Arbeitsleistung als korrekt abgenommen. Die gelieferte Ware bleibt bis zur restlosen Bezahlung das Eigentum des Auftragnehmers. Es gelten die Allgemeinen Geschäftsbedingungen des Auftraggebers. Für Materialien und Ersatzteile gelten die Gewährleistungsbedingungen des Herstellers.';for(const s of wrap(legal,152).slice(0,4)){txt(s,L,y,5.9,regular,gray);y-=7}if(settings?.report_footer&&y>66){y-=2;for(const s of wrap(String(settings.report_footer),152).slice(0,1)){txt(s,L,y,5.9,regular,gray);y-=7}}
 rule(48,red,1);const company=[settings?.company_name||'Design Tischlerei Schunk',settings?.street||'Industriestr. 9',`${settings?.postal_code||'53359'} ${settings?.city||'Rheinbach'}`,settings?.phone?`Tel. ${settings.phone}`:'Tel. 02226 895 985 3',settings?.email||'info@t-schunk.de',settings?.website||'www.t-schunk.de'].filter(Boolean).join('  ·  ');txt(company.slice(0,150),L,30,6.5,regular,gray);
 const bytes=await pdf.save(),path=`reports/${r.id}/${Date.now()}_${r.report_no}.pdf`;const {error:up}=await db.storage.from('schunk-private').upload(path,bytes,{contentType:'application/pdf',upsert:false});if(up)throw up;const {data:file,error:fe}=await db.from('files').insert({entity_type:'report',entity_id:r.id,category:'report_pdf',title:`Arbeitsbericht ${r.report_no}`,file_name:`${r.report_no}.pdf`,storage_path:path,mime_type:'application/pdf',size_bytes:bytes.length,upload_status:'ready',uploaded_by:u.id}).select().single();if(fe)throw fe;await db.from('work_reports').update({pdf_file_id:file.id}).eq('id',r.id);const {data:urlData,error:urlError}=await db.storage.from('schunk-private').createSignedUrl(path,300,{download:`${r.report_no}.pdf`});if(urlError)throw urlError;await audit(u.id,'generate_pdf','work_report',r.id);return NextResponse.json({file_id:file.id,url:urlData.signedUrl});
}catch(e){return errorResponse(e)}}
