import { NextRequest, NextResponse } from 'next/server';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { ApiError, audit, errorResponse, requireUser } from '@/lib/api-auth';
import { supabaseAdmin } from '@/lib/supabase-server';
import { LOGO_PNG_BASE64 } from '@/lib/logo-data';
import { requireReportAccess } from '@/lib/entity-access';
export const runtime='nodejs'; export const dynamic='force-dynamic';
function safe(v:any){return String(v??'');} function min(v:number){return `${Math.floor(v/60)}:${String(v%60).padStart(2,'0')}`}
export async function POST(req:NextRequest){try{const u=await requireUser(req,'reports.read');const {id}=await req.json();await requireReportAccess(u,id);const db=supabaseAdmin();const {data:r,error}=await db.from('work_reports').select('*,construction_sites(project_no,title,street,postal_code,city,customers(name,salutation,street,postal_code,city)),work_report_members(*,profiles(full_name)),work_report_materials(*)').eq('id',id).single();if(error||!r)throw error||new ApiError(404,'Rapport nicht gefunden.');
const {data:settings}=await db.from('portal_settings').select('*').eq('id',1).maybeSingle();const pdf=await PDFDocument.create();const page=pdf.addPage([595.28,841.89]);const {width,height}=page.getSize();const regular=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);const red=rgb(.87,.09,.12),black=rgb(.05,.06,.07),gray=rgb(.42,.45,.49),line=rgb(.86,.87,.89);let y=height-42;
page.drawRectangle({x:0,y:height-118,width,height:118,color:black});const logo=await pdf.embedPng(Buffer.from(LOGO_PNG_BASE64,'base64'));const ld=logo.scaleToFit(190,82);page.drawImage(logo,{x:36,y:height-106,width:ld.width,height:ld.height});page.drawText('ARBEITSBERICHT',{x:310,y:height-70,size:19,font:bold,color:rgb(1,1,1)});page.drawText(`Rapport ${safe(r.report_no)}`,{x:310,y:height-91,size:9,font:regular,color:rgb(.75,.78,.8)});y=height-145;
const label=(t:string,x:number,yy:number)=>page.drawText(t.toUpperCase(),{x,y:yy,size:7,font:bold,color:gray});const val=(t:string,x:number,yy:number,size=9)=>page.drawText(t||'—',{x,y:yy,size,font:regular,color:black});
label('Auftraggeber',42,y);label('Ausführungsort',310,y);y-=16;val(`${safe(r.customer_salutation||r.construction_sites?.customers?.salutation)} ${safe(r.customer_name||r.construction_sites?.customers?.name)}`.trim(),42,y);val(safe(r.construction_sites?.title),310,y);y-=13;val(`${safe(r.construction_sites?.customers?.street)} ${safe(r.construction_sites?.customers?.postal_code)} ${safe(r.construction_sites?.customers?.city)}`.trim(),42,y,8);val(`${safe(r.construction_sites?.street)} ${safe(r.construction_sites?.postal_code)} ${safe(r.construction_sites?.city)}`.trim(),310,y,8);y-=28;page.drawLine({start:{x:42,y:y+10},end:{x:553,y:y+10},thickness:1,color:line});label('Arbeitsbeschreibung / ausgeführte Arbeiten',42,y);y-=17;const desc=safe(r.work_description).slice(0,450);for(const chunk of wrap(desc,88).slice(0,4)){val(chunk,42,y,9);y-=12}y-=7;
label('Arbeitszeit',42,y);y-=18;const cols=[42,170,260,320,370,435,500];['Datum / Name','von','bis','Pause','Fahrt/Rüst','Gesamt',''].forEach((h,i)=>{if(h)page.drawText(h,{x:cols[i],y,size:7,font:bold,color:gray})});y-=11;page.drawLine({start:{x:42,y:y+5},end:{x:553,y:y+5},thickness:.7,color:line});for(const m of (r.work_report_members||[]).slice(0,6)){val(`${safe(r.work_date)}  ${safe(m.profiles?.full_name)}`,42,y,8);val(safe(m.start_time).slice(0,5),170,y,8);val(safe(m.end_time).slice(0,5),260,y,8);val(`${m.pause_minutes} min`,320,y,8);val(`${m.travel_setup_minutes} min`,370,y,8);val(`${min(m.total_minutes)} h`,435,y,8);y-=18;page.drawLine({start:{x:42,y:y+6},end:{x:553,y:y+6},thickness:.4,color:line})}y-=5;
label('Verarbeitetes Material',42,y);y-=18;page.drawText('Menge',{x:42,y,size:7,font:bold,color:gray});page.drawText('Einheit',{x:105,y,size:7,font:bold,color:gray});page.drawText('Beschreibung',{x:170,y,size:7,font:bold,color:gray});y-=12;for(const m of (r.work_report_materials||[]).slice(0,6)){val(safe(m.quantity),42,y,8);val(safe(m.unit),105,y,8);val(safe(m.description).slice(0,62),170,y,8);y-=17}y-=6;
label('Bemerkungen',42,y);y-=16;for(const chunk of wrap(safe(r.remarks),92).slice(0,3)){val(chunk,42,y,8);y-=11}y-=10;val(r.work_completed===true?'[X] Arbeiten abgeschlossen':'[ ] Arbeiten abgeschlossen',42,y,8);val(r.work_completed===false?'[X] Arbeiten nicht abgeschlossen':'[ ] Arbeiten nicht abgeschlossen',220,y,8);y-=34;
const {data:sigFiles}=await db.from('files').select('*').eq('entity_type','report').eq('entity_id',r.id).eq('upload_status','ready').in('category',['signature_customer','signature_employee']).order('created_at',{ascending:false});
async function drawSig(category:string,x:number,w:number){const f=(sigFiles||[]).find((z:any)=>z.category===category);if(!f)return;const {data:blob,error:de}=await db.storage.from('schunk-private').download(f.storage_path);if(de||!blob)return;const bytes=new Uint8Array(await blob.arrayBuffer());try{const im=await pdf.embedPng(bytes);const d=im.scaleToFit(w,46);page.drawImage(im,{x:x+(w-d.width)/2,y:y+4,width:d.width,height:d.height})}catch{}}
await drawSig('signature_customer',42,228);await drawSig('signature_employee',325,228);page.drawLine({start:{x:42,y},end:{x:270,y},thickness:.7,color:gray});page.drawLine({start:{x:325,y},end:{x:553,y},thickness:.7,color:gray});label('Datum / Unterschrift Auftraggeber (Kunde)',42,y-13);label('Datum / Unterschrift Auftragnehmer',325,y-13);y-=34;const legal='Der Kunde / Bevollmächtigte erkennt mit seiner Unterschrift die Arbeitszeit und den Materialverbrauch an. Ebenso wird die Arbeitsleistung als korrekt abgenommen. Die gelieferte Ware bleibt bis zur restlosen Bezahlung das Eigentum des Auftragnehmers. Es gelten die Allgemeinen Geschäftsbedingungen des Auftraggebers. Für Materialien und Ersatzteile gelten die Gewährleistungsbedingungen des Herstellers.';for(const chunk of wrap(legal,136).slice(0,4)){page.drawText(chunk,{x:42,y,size:6.2,font:regular,color:gray});y-=8}if(settings?.report_footer){for(const chunk of wrap(String(settings.report_footer),136).slice(0,2)){page.drawText(chunk,{x:42,y,size:6.2,font:regular,color:gray});y-=8}}const company=[settings?.company_name||'Design Tischlerei Schunk',settings?.street||'Industriestr. 9',`${settings?.postal_code||'53359'} ${settings?.city||'Rheinbach'}`,settings?.phone?`Tel. ${settings.phone}`:'Tel. 02226 895 985 3',settings?.email||'info@t-schunk.de',settings?.website||'www.t-schunk.de'].filter(Boolean).join(' · ');page.drawText(company.slice(0,145),{x:42,y:28,size:7,font:regular,color:gray});page.drawRectangle({x:0,y:0,width:595.28,height:8,color:red});
const bytes=await pdf.save();const path=`reports/${r.id}/${Date.now()}_${r.report_no}.pdf`;const {error:up}=await db.storage.from('schunk-private').upload(path,bytes,{contentType:'application/pdf',upsert:false});if(up)throw up;const {data:file,error:fe}=await db.from('files').insert({entity_type:'report',entity_id:r.id,category:'report_pdf',title:`Arbeitsbericht ${r.report_no}`,file_name:`${r.report_no}.pdf`,storage_path:path,mime_type:'application/pdf',size_bytes:bytes.length,upload_status:'ready',uploaded_by:u.id}).select().single();if(fe)throw fe;await db.from('work_reports').update({pdf_file_id:file.id}).eq('id',r.id);const {data:urlData,error:urlError}=await db.storage.from('schunk-private').createSignedUrl(path,300,{download:`${r.report_no}.pdf`});if(urlError)throw urlError;await audit(u.id,'generate_pdf','work_report',r.id);return NextResponse.json({file_id:file.id,url:urlData.signedUrl})}catch(e){return errorResponse(e)}}
function wrap(text:string,max:number){if(!text)return ['—'];const words=text.split(/\s+/);const lines:string[]=[];let cur='';for(const w of words){if((cur+' '+w).trim().length>max){lines.push(cur);cur=w}else cur=(cur+' '+w).trim()}if(cur)lines.push(cur);return lines}
