import {NextRequest,NextResponse} from 'next/server';import {errorResponse,requireUser} from '@/lib/api-auth';import {supabaseAdmin} from '@/lib/supabase-server';
const feeds=['reports','photos','orders','messages','defects','measurements','tasks'];
export async function GET(req:NextRequest){try{const u=await requireUser(req,'dashboard.read'),db=supabaseAdmin();const {data:seen}=await db.from('user_seen_state').select('*').eq('user_id',u.id);const sm=new Map((seen||[]).map((x:any)=>[x.feed_type,x.seen_at]));const since=(k:string)=>sm.get(k)||'1970-01-01T00:00:00Z';const wide=u.roles.includes('admin');
let siteIds:string[]=[];if(!wide){const {data:m}=await db.from('construction_members').select('construction_site_id').eq('user_id',u.id);siteIds=(m||[]).map((x:any)=>x.construction_site_id)}
const counts:any={};
let rq=db.from('work_reports').select('id',{count:'exact',head:true}).gt('updated_at',since('reports'));if(!wide&&siteIds.length)rq=rq.in('construction_site_id',siteIds);else if(!wide&&!siteIds.length)rq=rq.eq('created_by',u.id);counts.reports=(await rq).count||0;
let pq=db.from('files').select('id,entity_type,entity_id,uploaded_by,category',{count:'exact'}).like('mime_type','image/%').eq('upload_status','ready').gt('created_at',since('photos'));const pr=await pq;let photos=(pr.data||[]).filter((f:any)=>!['signature_customer','signature_employee'].includes(f.category));if(!wide){const reportIds=siteIds.length?(await db.from('work_reports').select('id').in('construction_site_id',siteIds)).data?.map((x:any)=>x.id)||[]:[];photos=photos.filter((f:any)=>f.uploaded_by===u.id||f.entity_type==='site'&&siteIds.includes(f.entity_id)||f.entity_type==='report'&&reportIds.includes(f.entity_id))}counts.photos=photos.length;
let oq=db.from('purchase_requests').select('id',{count:'exact',head:true}).gt('created_at',since('orders'));if(!wide)oq=oq.eq('created_by',u.id);counts.orders=(await oq).count||0;
let ownMsgQ=db.from('internal_messages').select('id');if(!wide)ownMsgQ=ownMsgQ.or(`sender_id.eq.${u.id},recipient_id.eq.${u.id}`);const ownMsgs=(await ownMsgQ).data||[],msgIds=ownMsgs.map((x:any)=>x.id);let mq=db.from('internal_messages').select('id',{count:'exact',head:true}).gt('created_at',since('messages'));if(!wide)mq=mq.or(`sender_id.eq.${u.id},recipient_id.eq.${u.id}`);const newThreads=(await mq).count||0;let newReplies=0;if(msgIds.length){const rr=await db.from('internal_message_replies').select('id',{count:'exact',head:true}).in('message_id',msgIds).neq('user_id',u.id).gt('created_at',since('messages'));newReplies=rr.count||0}counts.messages=newThreads+newReplies;
let iq=db.from('project_items').select('id',{count:'exact',head:true}).in('item_type',['defect','problem']).gt('created_at',since('defects'));if(!wide&&siteIds.length)iq=iq.in('construction_site_id',siteIds);counts.defects=(await iq).count||0;
let mm=db.from('measurements').select('id',{count:'exact',head:true}).gt('created_at',since('measurements'));if(!wide&&siteIds.length)mm=mm.in('construction_site_id',siteIds);counts.measurements=(await mm).count||0;
let tq=db.from('project_tasks').select('id',{count:'exact',head:true}).gt('created_at',since('tasks'));if(!wide)tq=tq.eq('assigned_to',u.id);counts.tasks=(await tq).count||0;
return NextResponse.json(counts)}catch(e){return errorResponse(e)}}
export async function POST(req:NextRequest){try{const u=await requireUser(req,'dashboard.read'),b=await req.json(),feed=String(b.feed||'');if(!feeds.includes(feed))return NextResponse.json({error:'Ungültiger Bereich.'},{status:400});const {error}=await supabaseAdmin().from('user_seen_state').upsert({user_id:u.id,feed_type:feed,seen_at:new Date().toISOString()},{onConflict:'user_id,feed_type'});if(error)throw error;return NextResponse.json({ok:true})}catch(e){return errorResponse(e)}}