'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { PageHeader } from '@/components/PageHeader';
import { useAuth } from '@/components/AuthProvider';
import { apiFetch } from '@/lib/api-client';

type D={stats:{sites:number;todayMinutes:number;openReports:number;openTasks:number;urgent:number;messages:number};sites:any[];urgent:any[];messages:any[]};
export default function Dashboard(){const {accessToken,me}=useAuth();const [data,setData]=useState<D|null>(null);const [err,setErr]=useState('');useEffect(()=>{apiFetch<D>('/api/dashboard',accessToken).then(setData).catch(e=>setErr(e.message))},[accessToken]);return <><PageHeader eyebrow="ÜBERSICHT" title={`Guten Tag, ${me?.full_name?.split(' ')[0]||''}.`} text="Aktuelle Baustellen, Arbeitszeiten und offene Punkte auf einen Blick."/>{err&&<div className="alert error">{err}</div>}<div className="stats"><div className="stat"><span>Aktive Baustellen</span><strong>{data?.stats.sites??'–'}</strong><small>im Zugriff</small></div><div className="stat"><span>Arbeitszeit heute</span><strong>{data?`${Math.floor(data.stats.todayMinutes/60)}:${String(data.stats.todayMinutes%60).padStart(2,'0')}`:'–'}</strong><small>Stunden</small></div><div className="stat"><span>Offene Rapporte</span><strong>{data?.stats.openReports??'–'}</strong><small>noch nicht abgeschlossen</small></div><div className="stat"><span>Offene Aufgaben</span><strong>{data?.stats.openTasks??'–'}</strong><small>zu bearbeiten</small></div><div className="stat"><span>Dringende Meldungen</span><strong>{data?.stats.urgent??'–'}</strong><small>Mängel / Probleme</small></div><div className="stat"><span>Nachrichten an mich</span><strong>{data?.stats.messages??'–'}</strong><small>offen</small></div></div>{data?.urgent?.length?<div className="card"><div className="section-title"><h2>Dringende Mängel & Probleme</h2></div>{data.urgent.map(x=><Link key={x.id} className="issue-row" href={`/baustellen?id=${x.construction_site_id}&item=${x.id}`}><span className="badge red">Dringend</span><div><strong>{x.title}</strong><div className="muted">{x.construction_sites?.project_no} · {x.construction_sites?.title}</div></div></Link>)}</div>:null}{data?.messages?.length?<div className="card"><div className="section-title"><h2>Nachrichten an mich</h2></div>{data.messages.map(x=><Link key={x.id} className="issue-row" href={`/baustellen?id=${x.construction_site_id}&item=${x.id}`}><span className="badge">Neu</span><div><strong>{x.title}</strong><div className="muted">{x.construction_sites?.project_no} · {x.construction_sites?.title}</div></div></Link>)}</div>:null}<div className="card"><div className="section-title"><h2>Aktuelle Baustellen</h2><Link className="btn" href="/baustellen">Alle Baustellen</Link></div>{data?.sites?.length?<div className="site-grid">{data.sites.map(s=><Link key={s.id} className="site-card" href={`/baustellen?id=${s.id}`}><span className={`badge ${s.priority==='Kritisch'?'red':s.status==='Aktiv'?'green':''}`}>{s.status}</span><h3>{s.title}</h3><p className="muted">{s.project_no} · {s.city||'ohne Ort'}</p></Link>)}</div>:<div className="empty">Noch keine Baustellen vorhanden.</div>}</div></>}
