'use client';
import { useRef, useState } from 'react';
import { UploadCloud } from 'lucide-react';
import { useAuth } from './AuthProvider';
import { apiFetch } from '@/lib/api-client';
import { getSupabaseBrowser } from '@/lib/supabase-browser';

type Props={entityType:'site'|'report'|'profile'|'project_item';entityId:string;category:string;accept?:string;label?:string;title?:string;description?:string;visibility?:'admin'|'office'|'site_members'|'selected';visibleTo?:string[];onUploaded?:()=>void};
export function FileUploader({entityType,entityId,category,accept,label='Datei hochladen',title,description,visibility='site_members',visibleTo=[],onUploaded}:Props){const {accessToken}=useAuth();const input=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function pick(file?:File){if(!file)return;setBusy(true);setError('');try{const prep=await apiFetch<{file_id:string;bucket:string;path:string;token:string}>('/api/files/upload-url',accessToken,{method:'POST',body:JSON.stringify({entity_type:entityType,entity_id:entityId,category,title:title||file.name,description:description||null,visibility,visible_to:visibleTo,file_name:file.name,mime_type:file.type,size_bytes:file.size})});const {error:up}=await getSupabaseBrowser().storage.from(prep.bucket).uploadToSignedUrl(prep.path,prep.token,file,{contentType:file.type||undefined});if(up)throw up;await apiFetch('/api/files/complete',accessToken,{method:'POST',body:JSON.stringify({file_id:prep.file_id})});onUploaded?.()}catch(e){setError(e instanceof Error?e.message:'Upload fehlgeschlagen.')}finally{setBusy(false);if(input.current)input.current.value=''}}return <div><input ref={input} type="file" accept={accept} hidden onChange={e=>pick(e.target.files?.[0])}/><button className="btn" disabled={busy} onClick={()=>input.current?.click()}><UploadCloud size={17} style={{verticalAlign:'middle',marginRight:7}}/>{busy?'Upload…':label}</button>{error&&<div className="alert error">{error}</div>}</div>}
