import { NextRequest, NextResponse } from 'next/server';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import ExcelJS from 'exceljs';
import { ApiError,errorResponse,requireUser } from '@/lib/api-auth';
import { supabaseAdmin } from '@/lib/supabase-server';
export const runtime='nodejs'; export const dynamic='force-dynamic';
function hm(v:number){const s=v<0?'-':'';v=Math.abs(v||0);return `${s}${Math.floor(v/60)}:${String(v%60).padStart(2,'0')}`}
function fmtDate(v:string){return new Intl.DateTimeFormat('de-DE').format(new Date(v+'T12:00:00'))}
async function load(req:NextRequest){const u=await requireUser(req,'time.own');const db=supabaseAdmin();const month=req.nextUrl.searchParams.get('month')||new Date().toISOString().slice(0,7);const requested=req.nextUrl.searchParams.get('user_id')||u.id;if(requested!==u.id&&!u.roles.includes('admin')&&!u.permissions.includes('time.all'))throw new ApiError(403,'Keine Berechtigung für fremde Zeiten.');const [y,m]=month.split('-').map(Number);const start=`${month}-01`;const end=new Date(Date.UTC(y,m,0)).toISOString().slice(0,10);const {data:profile,error:pe}=await db.from('profiles').select('full_name,weekly_hours').eq('id',requested).single();if(pe)throw pe;const {data:entries,error}=await db.from('time_entries').select('*,construction_sites(project_no,title)').eq('user_id',requested).gte('work_date',start).lte('work_date',end).order('work_date').order('start_time');if(error)throw error;const {data:abs,error:ae}=await db.from('absences').select('*').eq('user_id',requested).lte('start_date',end).gte('end_date',start).eq('status','Genehmigt');if(ae)throw ae;const actual=(entries||[]).reduce((s:number,x:any)=>s+Number(x.total_minutes||0),0);return {month,profile,entries:entries||[],abs:abs||[],actual}}
export async function GET(req:NextRequest){try{const d=await load(req);const format=req.nextUrl.searchParams.get('format')||'pdf';const safeName=String(d.profile.full_name||'Mitarbeiter').replace(/[^a-zA-Z0-9äöüÄÖÜß_-]+/g,'_');if(format==='xlsx'){const wb=new ExcelJS.Workbook();wb.creator='SCHUNK PORTAL';wb.created=new Date();const ws=wb.addWorksheet('Arbeitszeiten');ws.columns=[{header:'Datum',key:'date',width:13},{header:'Baustelle',key:'site',width:32},{header:'Von',key:'from',width:10},{header:'Bis',key:'to',width:10},{header:'Pause (min)',key:'pause',width:14},{header:'Fahrt/Rüst (min)',key:'travel',width:18},{header:'Gesamt',key:'total',width:12},{header:'Tätigkeit',key:'activity',width:40},{header:'Bemerkung',key:'notes',width:40}];ws.getRow(1).font={bold:true};for(const x of d.entries)ws.addRow({date:fmtDate(x.work_date),site:x.construction_sites?`${x.construction_sites.project_no||''} ${x.construction_sites.title||''}`.trim():'Allgemein',from:String(x.start_time).slice(0,5),to:String(x.end_time).slice(0,5),pause:x.pause_minutes,travel:x.travel_setup_minutes,total:hm(x.total_minutes),activity:x.activity||'',notes:x.notes||''});ws.addRow({});ws.addRow({activity:'Gesamt Ist',total:hm(d.actual)});ws.addRow({activity:'Wochenstunden laut Profil',total:String(d.profile.weekly_hours||40)});const ab=wb.addWorksheet('Abwesenheiten');ab.columns=[{header:'Art',key:'type',width:22},{header:'Von',key:'from',width:13},{header:'Bis',key:'to',width:13},{header:'Status',key:'status',width:16},{header:'Bemerkung',key:'notes',width:40}];ab.getRow(1).font={bold:true};for(const a of d.abs)ab.addRow({type:a.absence_type,from:fmtDate(a.start_date),to:fmtDate(a.end_date),status:a.status,notes:a.notes||''});const buf=await wb.xlsx.writeBuffer();return new NextResponse(Buffer.from(buf),{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="Arbeitszeiten_${safeName}_${d.month}.xlsx"`}})}
const pdf=await PDFDocument.create();const regular=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);let page=pdf.addPage([841.89,595.28]);let y=555;const black=rgb(.05,.06,.07),gray=rgb(.4,.43,.47),red=rgb(.87,.09,.12);const drawHeader=()=>{page.drawRectangle({x:0,y:550,width:842,height:45,color:black});page.drawText('SCHUNK PORTAL · ARBEITSZEITEN',{x:32,y:566,size:14,font:bold,color:rgb(1,1,1)});page.drawText(`${d.profile.full_name} · ${d.month}`,{x:580,y:566,size:9,font:regular,color:rgb(.85,.85,.85)});y=525;};drawHeader();const cols=[32,110,320,375,425,480,555,620];const heads=['Datum','Baustelle','Von','Bis','Pause','Fahrt/Rüst','Gesamt','Tätigkeit'];heads.forEach((h,i)=>page.drawText(h,{x:cols[i],y,size:7,font:bold,color:gray}));y-=14;for(const x of d.entries){if(y<55){page=pdf.addPage([841.89,595.28]);drawHeader();heads.forEach((h,i)=>page.drawText(h,{x:cols[i],y,size:7,font:bold,color:gray}));y-=14;}const site=x.construction_sites?`${x.construction_sites.project_no||''} ${x.construction_sites.title||''}`.trim():'Allgemein';const vals=[fmtDate(x.work_date),site.slice(0,34),String(x.start_time).slice(0,5),String(x.end_time).slice(0,5),`${x.pause_minutes} min`,`${x.travel_setup_minutes} min`,`${hm(x.total_minutes)} h`,String(x.activity||'').slice(0,30)];vals.forEach((v,i)=>page.drawText(v,{x:cols[i],y,size:7.5,font:regular,color:black}));y-=15;}y-=10;page.drawText(`Gesamt Ist: ${hm(d.actual)} h`,{x:32,y,size:10,font:bold,color:red});const bytes=await pdf.save();return new NextResponse(Buffer.from(bytes),{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="Arbeitszeiten_${safeName}_${d.month}.pdf"`}})}catch(e){return errorResponse(e)}}
