import {NextRequest,NextResponse} from 'next/server';
import {ApiError,audit,errorResponse,requireUser} from '@/lib/api-auth';
import {supabaseAdmin} from '@/lib/supabase-server';
import {requireSiteMembership,requireTaskAccess} from '@/lib/entity-access';
export const dynamic='force-dynamic';
export async function GET(req:NextRequest){try{const u=await requireUser(req,'sites.read');const db=supabaseAdmin();const id=req.nextUrl.searchParams.get('id');
 if(id){await requireTaskAccess(u,id);const {data,error}=await db.from('project_tasks').select('*,construction_sites(id,project_no,title),section:project_sections(id,name),assignee:profiles!project_tasks_assigned_to_fkey(id,full_name),creator:profiles!project_tasks_created_by_fkey(id,full_name),project_task_comments(*,profiles(full_name))').eq('id',id).single();if(error)throw error;const {data:files}=await db.from('files').select('*').eq('entity_type','task').eq('entity_id',id).eq('upload_status','ready').order('created_at');const broad=u.roles.some((r:string)=>['admin','office','foreman'].includes(r));const visibleFiles=broad?(files||[]):(files||[]).filter((f:any)=>f.visibility==='site_members'||(f.visibility==='selected'&&Array.isArray(f.visible_to)&&f.visible_to.includes(u.id)));return NextResponse.json({...data,files:visibleFiles})}
 let q=db.from('project_tasks').select('*,construction_sites(id,project_no,title),section:project_sections(id,name),assignee:profiles!project_tasks_assigned_to_fkey(id,full_name),creator:profiles!project_tasks_created_by_fkey(id,full_name)').order('created_at',{ascending:false});
 if(!u.roles.some((r:string)=>['admin','office','foreman'].includes(r))){const {data:m}=await db.from('construction_members').select('construction_site_id').eq('user_id',u.id);const ids=(m||[]).map((x:any)=>x.construction_site_id);q=ids.length?q.or(`construction_site_id.in.(${ids.join(',')}),created_by.eq.${u.id},assigned_to.eq.${u.id}`):q.or(`created_by.eq.${u.id},assigned_to.eq.${u.id}`)}
 const {data,error}=await q;if(error)throw error;return NextResponse.json(data||[]);
}catch(e){return errorResponse(e)}}
export async function POST(req:NextRequest){try{const u=await requireUser(req,'sites.read');const b=await req.json();if(!String(b.title||'').trim())throw new ApiError(400,'Überschrift ist Pflicht.');if(b.construction_site_id)await requireSiteMembership(u,b.construction_site_id);const db=supabaseAdmin();const {data,error}=await db.from('project_tasks').insert({construction_site_id:b.construction_site_id||null,section_id:b.section_id||null,title:String(b.title).trim(),description:b.description||null,assigned_to:b.assigned_to||null,due_date:b.due_date||null,priority:b.priority||'Normal',status:b.status||'Offen',created_by:u.id}).select().single();if(error)throw error;await audit(u.id,'create','task',data.id);return NextResponse.json(data)}catch(e){return errorResponse(e)}}
export async function PATCH(req:NextRequest){try{const u=await requireUser(req,'sites.read');const b=await req.json();const current=await requireTaskAccess(u,b.id);const wide=u.roles.some((r:string)=>['admin','office','foreman'].includes(r));if(!wide&&current.created_by!==u.id&&current.assigned_to!==u.id)throw new ApiError(403,'Keine Berechtigung zum Bearbeiten dieser Aufgabe.');if('construction_site_id' in b&&b.construction_site_id)await requireSiteMembership(u,b.construction_site_id);const db=supabaseAdmin();const values:any={updated_at:new Date().toISOString()};for(const k of ['construction_site_id','section_id','title','description','assigned_to','due_date','priority','status'])if(k in b)values[k]=b[k]||null;if(values.status==='Erledigt')values.completed_at=new Date().toISOString();const {data,error}=await db.from('project_tasks').update(values).eq('id',b.id).select().single();if(error)throw error;await audit(u.id,'update','task',b.id,values);return NextResponse.json(data)}catch(e){return errorResponse(e)}}
export async function DELETE(req:NextRequest){try{const u=await requireUser(req,'sites.read');if(!u.roles.includes('admin'))throw new ApiError(403,'Nur Administratoren dürfen Aufgaben löschen.');const id=req.nextUrl.searchParams.get('id');if(!id)throw new ApiError(400,'ID fehlt.');const db=supabaseAdmin();await db.from('project_tasks').delete().eq('id',id);await audit(u.id,'delete','task',id);return NextResponse.json({ok:true})}catch(e){return errorResponse(e)}}
